#!/usr/bin/env bash

set -e

mkdir -p "$HOME/personal"

git clone --branch stable https://github.com/neovim/neovim.git $HOME/personal/neovim
sudo apt install -y ninja-build gettext libtool libtool-bin autoconf automake cmake g++ pkg-config unzip curl doxygen

cd $HOME/personal/neovim
make CMAKE_BUILD_TYPE=RelWithDebInfo
sudo make install
